export const demoUsers = {
  demo1: {
    id: "demo1",
    full_name: "Alex Chen",
    avatar_url: "/avatars/alex.jpg",
    status: "Frontend developer passionate about React and TypeScript",
    location: "Melbourne, Australia",
  },
  demo2: {
    id: "demo2",
    full_name: "Sarah Kumar",
    avatar_url: "/avatars/sarah.jpg",
    status: "ML engineer specializing in computer vision and deep learning",
    location: "Sydney, Australia",
  },
  demo3: {
    id: "demo3",
    full_name: "Marcus Johnson",
    avatar_url: "/avatars/marcus.jpg",
    status: "AI researcher focused on healthcare applications",
    location: "Melbourne, Australia",
  },
  demo4: {
    id: "demo4",
    full_name: "Emma Rodriguez",
    avatar_url: "/avatars/emma.jpg",
    status: "Robotics engineer working on autonomous systems",
    location: "Brisbane, Australia",
  },
  demo5: {
    id: "demo5",
    full_name: "David Park",
    avatar_url: "/avatars/david.jpg",
    status: "Business student with experience in startup operations",
    location: "Melbourne, Australia",
  },
  demo6: {
    id: "demo6",
    full_name: "Lisa Wang",
    avatar_url: "/avatars/lisa.jpg",
    status: "Product manager with background in fintech and edtech",
    location: "Melbourne, Australia",
  },
  demo7: {
    id: "demo7",
    full_name: "Ryan Thompson",
    avatar_url: "/avatars/ryan.jpg",
    status: "Software engineer intern at Google, mentor for coding interviews",
    location: "Melbourne, Australia",
  },
  demo8: {
    id: "demo8",
    full_name: "Priya Patel",
    avatar_url: "/avatars/priya.jpg",
    status: "Product management intern at Microsoft, interview coach",
    location: "Perth, Australia",
  },
  demo9: {
    id: "demo9",
    full_name: "Jake Miller",
    avatar_url: "/avatars/jake.jpg",
    status: "Data science student leading ML study groups and competitions",
    location: "Melbourne, Australia",
  },
  demo10: {
    id: "demo10",
    full_name: "Sophia Lee",
    avatar_url: "/avatars/sophia.jpg",
    status: "PhD student in data science, tutor for undergraduate courses",
    location: "Melbourne, Australia",
  },
  demo11: {
    id: "demo11",
    full_name: "Kevin Zhang",
    avatar_url: "/avatars/kevin.jpg",
    status: "NLP researcher working on conversational AI systems",
    location: "Melbourne, Australia",
  },
  demo12: {
    id: "demo12",
    full_name: "Maya Singh",
    avatar_url: "/avatars/maya.jpg",
    status: "Computer science student exploring AI applications in healthcare",
    location: "Adelaide, Australia",
  },
  demo13: {
    id: "demo13",
    full_name: "Rachel Adams",
    avatar_url: "/avatars/rachel.jpg",
    status: "Data Science Student Society President, industry connector",
    location: "Melbourne, Australia",
  },
  demo14: {
    id: "demo14",
    full_name: "Tom Wilson",
    avatar_url: "/avatars/tom.jpg",
    status: "Analytics Club VP, Kaggle competition enthusiast",
    location: "Melbourne, Australia",
  },
  demo15: {
    id: "demo15",
    full_name: "Green Earth Society",
    avatar_url: "/avatars/green.jpg",
    status: "Environmental club organizing sustainability initiatives",
    location: "Melbourne, Australia",
  },
  demo16: {
    id: "demo16",
    full_name: "Climate Action Melbourne",
    avatar_url: "/avatars/climate.jpg",
    status: "Student-led climate advocacy and policy discussion group",
    location: "Melbourne, Australia",
  },
  demo17: {
    id: "demo17",
    full_name: "DSSS Committee",
    avatar_url: "/avatars/dsss.jpg",
    status: "Data Science Student Society official committee",
    location: "Melbourne, Australia",
  },
  demo18: {
    id: "demo18",
    full_name: "Anna Chen",
    avatar_url: "/avatars/anna.jpg",
    status: "DSSS Membership Coordinator, helping students connect",
    location: "Melbourne, Australia",
  },
  demo19: {
    id: "demo19",
    full_name: "International Student Society",
    avatar_url: "/avatars/iss.jpg",
    status: "Supporting international students with events and community",
    location: "Melbourne, Australia",
  },
  demo20: {
    id: "demo20",
    full_name: "Asian Cultural Society",
    avatar_url: "/avatars/asian.jpg",
    status: "Celebrating Asian heritage through cultural events and festivals",
    location: "Melbourne, Australia",
  },
  demo21: {
    id: "demo21",
    full_name: "Alex Kim",
    avatar_url: "/avatars/alexk.jpg",
    status: "ACM ICPC competitor, algorithms and data structures expert",
    location: "Melbourne, Australia",
  },
  demo22: {
    id: "demo22",
    full_name: "Jordan Lee",
    avatar_url: "/avatars/jordan.jpg",
    status: "Codeforces expert, competitive programming mentor",
    location: "Melbourne, Australia",
  },
  demo23: {
    id: "demo23",
    full_name: "Tech Connect Melbourne",
    avatar_url: "/avatars/tech.jpg",
    status: "Tech industry networking events and career connections",
    location: "Melbourne, Australia",
  },
  demo24: {
    id: "demo24",
    full_name: "Startup Mixer",
    avatar_url: "/avatars/startup.jpg",
    status: "Entrepreneurship community connecting founders and investors",
    location: "Melbourne, Australia",
  },
  demo25: {
    id: "demo25",
    full_name: "AI Challenge 2024",
    avatar_url: "/avatars/ai.jpg",
    status: "National AI hackathon bringing together innovative minds",
    location: "Melbourne, Australia",
  },
  demo26: {
    id: "demo26",
    full_name: "Mathematical Modelling Contest",
    avatar_url: "/avatars/math.jpg",
    status: "Team-based mathematical problem solving competition",
    location: "Melbourne, Australia",
  },
  demo27: {
    id: "demo27",
    full_name: "Career Fair Coffee Chat",
    avatar_url: "/avatars/career.jpg",
    status: "Informal career networking over coffee and pastries",
    location: "Melbourne, Australia",
  },
  demo28: {
    id: "demo28",
    full_name: "Study Break Social",
    avatar_url: "/avatars/social.jpg",
    status: "Relaxed study break with refreshments and socializing",
    location: "Melbourne, Australia",
  },
  demo29: {
    id: "demo29",
    full_name: "AI Research Seminar",
    avatar_url: "/avatars/research.jpg",
    status: "Academic seminar on latest machine learning developments",
    location: "Melbourne, Australia",
  },
  demo30: {
    id: "demo30",
    full_name: "AI Ethics Workshop",
    avatar_url: "/avatars/ethics.jpg",
    status: "Interactive discussion on responsible AI development",
    location: "Melbourne, Australia",
  },
  demo31: {
    id: "demo31",
    full_name: "Python Bootcamp Series",
    avatar_url: "/avatars/python.jpg",
    status: "Comprehensive Python learning from basics to advanced topics",
    location: "Melbourne, Australia",
  },
  demo32: {
    id: "demo32",
    full_name: "Code Academy Study Group",
    avatar_url: "/avatars/code.jpg",
    status: "Peer-led programming practice with hands-on projects",
    location: "Melbourne, Australia",
  },
};
