export interface UserDetails {
  user_id: string;
  name: string;
  avatar?: string;
  status: string;
  location: string;
}

export const demoUsers: Record<string, UserDetails> = {
  demo1: {
    user_id: "demo1",
    name: "Alex Chen",
    avatar: undefined,
    status: "Frontend developer passionate about React and TypeScript",
    location: "Melbourne, Australia",
  },
  demo2: {
    user_id: "demo2",
    name: "Sarah Kumar",
    avatar: undefined,
    status: "ML engineer specializing in computer vision and deep learning",
    location: "Sydney, Australia",
  },
  demo3: {
    user_id: "demo3",
    name: "Marcus Johnson",
    avatar: undefined,
    status: "AI researcher focused on healthcare applications",
    location: "Melbourne, Australia",
  },
  demo4: {
    user_id: "demo4",
    name: "Emma Rodriguez",
    avatar: undefined,
    status: "Robotics engineer working on autonomous systems",
    location: "Brisbane, Australia",
  },
  demo5: {
    user_id: "demo5",
    name: "Davuser_id Park",
    avatar: undefined,
    status: "Business student with experience in startup operations",
    location: "Melbourne, Australia",
  },
  demo6: {
    user_id: "demo6",
    name: "Lisa Wang",
    avatar: undefined,
    status: "Product manager with background in fintech and edtech",
    location: "Melbourne, Australia",
  },
  demo7: {
    user_id: "demo7",
    name: "Ryan Thompson",
    avatar: undefined,
    status: "Software engineer intern at Google, mentor for coding interviews",
    location: "Melbourne, Australia",
  },
  demo8: {
    user_id: "demo8",
    name: "Priya Patel",
    avatar: undefined,
    status: "Product management intern at Microsoft, interview coach",
    location: "Perth, Australia",
  },
  demo9: {
    user_id: "demo9",
    name: "Jake Miller",
    avatar: undefined,
    status: "Data science student leading ML study groups and competitions",
    location: "Melbourne, Australia",
  },
  demo10: {
    user_id: "demo10",
    name: "Sophia Lee",
    avatar: undefined,
    status: "PhD student in data science, tutor for undergraduate courses",
    location: "Melbourne, Australia",
  },
  demo11: {
    user_id: "demo11",
    name: "Kevin Zhang",
    avatar: undefined,
    status: "NLP researcher working on conversational AI systems",
    location: "Melbourne, Australia",
  },
  demo12: {
    user_id: "demo12",
    name: "Maya Singh",
    avatar: undefined,
    status: "Computer science student exploring AI applications in healthcare",
    location: "Adelauser_ide, Australia",
  },
  demo13: {
    user_id: "demo13",
    name: "Rachel Adams",
    avatar: undefined,
    status: "Data Science Student Society Presuser_ident, industry connector",
    location: "Melbourne, Australia",
  },
  demo14: {
    user_id: "demo14",
    name: "Tom Wilson",
    avatar: undefined,
    status: "Analytics Club VP, Kaggle competition enthusiast",
    location: "Melbourne, Australia",
  },
  demo15: {
    user_id: "demo15",
    name: "Green Earth Society",
    avatar: undefined,
    status: "Environmental club organizing sustainability initiatives",
    location: "Melbourne, Australia",
  },
  demo16: {
    user_id: "demo16",
    name: "Climate Action Melbourne",
    avatar: undefined,
    status: "Student-led climate advocacy and policy discussion group",
    location: "Melbourne, Australia",
  },
  demo17: {
    user_id: "demo17",
    name: "DSSS Committee",
    avatar: undefined,
    status: "Data Science Student Society official committee",
    location: "Melbourne, Australia",
  },
  demo18: {
    user_id: "demo18",
    name: "Anna Chen",
    avatar: undefined,
    status: "DSSS Membership Coordinator, helping students connect",
    location: "Melbourne, Australia",
  },
  demo19: {
    user_id: "demo19",
    name: "International Student Society",
    avatar: undefined,
    status: "Supporting international students with events and community",
    location: "Melbourne, Australia",
  },
  demo20: {
    user_id: "demo20",
    name: "Asian Cultural Society",
    avatar: undefined,
    status: "Celebrating Asian heritage through cultural events and festivals",
    location: "Melbourne, Australia",
  },
  demo21: {
    user_id: "demo21",
    name: "Alex Kim",
    avatar: undefined,
    status: "ACM ICPC competitor, algorithms and data structures expert",
    location: "Melbourne, Australia",
  },
  demo22: {
    user_id: "demo22",
    name: "Jordan Lee",
    avatar: undefined,
    status: "Codeforces expert, competitive programming mentor",
    location: "Melbourne, Australia",
  },
  demo23: {
    user_id: "demo23",
    name: "Tech Connect Melbourne",
    avatar: undefined,
    status: "Tech industry networking events and career connections",
    location: "Melbourne, Australia",
  },
  demo24: {
    user_id: "demo24",
    name: "Startup Mixer",
    avatar: undefined,
    status: "Entrepreneurship community connecting founders and investors",
    location: "Melbourne, Australia",
  },
  demo25: {
    user_id: "demo25",
    name: "AI Challenge 2024",
    avatar: undefined,
    status: "National AI hackathon bringing together innovative minds",
    location: "Melbourne, Australia",
  },
  demo26: {
    user_id: "demo26",
    name: "Mathematical Modelling Contest",
    avatar: undefined,
    status: "Team-based mathematical problem solving competition",
    location: "Melbourne, Australia",
  },
  demo27: {
    user_id: "demo27",
    name: "Career Fair Coffee Chat",
    avatar: undefined,
    status: "Informal career networking over coffee and pastries",
    location: "Melbourne, Australia",
  },
  demo28: {
    user_id: "demo28",
    name: "Study Break Social",
    avatar: undefined,
    status: "Relaxed study break with refreshments and socializing",
    location: "Melbourne, Australia",
  },
  demo29: {
    user_id: "demo29",
    name: "AI Research Seminar",
    avatar: undefined,
    status: "Academic seminar on latest machine learning developments",
    location: "Melbourne, Australia",
  },
  demo30: {
    user_id: "demo30",
    name: "AI Ethics Workshop",
    avatar: undefined,
    status: "Interactive discussion on responsible AI development",
    location: "Melbourne, Australia",
  },
  demo31: {
    user_id: "demo31",
    name: "Python Bootcamp Series",
    avatar: undefined,
    status: "Comprehensive Python learning from basics to advanced topics",
    location: "Melbourne, Australia",
  },
  demo32: {
    user_id: "demo32",
    name: "Code Academy Study Group",
    avatar: undefined,
    status: "Peer-led programming practice with hands-on projects",
    location: "Melbourne, Australia",
  },
  "81cba4a3-a014-40a1-9417-f236ce967112": {
    user_id: "81cba4a3-a014-40a1-9417-f236ce967112",
    name: "DSCubed",
    avatar:
      "https://nsjrzxbtxsqmsdgevszv.supabase.co/storage/v1/object/public/avatars/81cba4a3-a014-40a1-9417-f236ce967112/92a33856-3818-4ec1-b4ee-c9d07fdfa76d.jpg",
    status: "Connecting students passionate about Data Science and AI",
    location: "Melbourne, Australia",
  },
  "f2d127bb-17de-4179-84af-0c008fddcdde": {
    user_id: "f2d127bb-17de-4179-84af-0c008fddcdde",
    name: "Data Science Club (DSC)",
    avatar:
      "https://nsjrzxbtxsqmsdgevszv.supabase.co/storage/v1/object/public/avatars/f2d127bb-17de-4179-84af-0c008fddcdde/6f90018f-7373-4691-a509-fbee81beccec.jpg",
    status: "University club aimed at job readiness through upskilling",
    location: "Melbourne, Australia",
  },
};
