"use client";
import { motion } from "framer-motion";
import AnimatedParticles from "@/components/AnimatedParticles";
import { ChunkCards } from "./ChunkCards";

export interface Chunk {
  chunk_id: string;
  category: string;
  content: string;
}

interface ChunksSectionProps {
  chunks?: Chunk[]; // initial chunks from parent
  setChunks?: (chunks: Chunk[]) => void; // optional setter for controlled usage
  isAIChunked?: boolean; // whether chunks were generated by AI
}

export default function ChunksSection({
  chunks = [],
  setChunks,
  isAIChunked,
}: ChunksSectionProps) {
  return (
    <motion.div
      className="relative max-w-4xl mx-auto"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      <ChunkCards chunks={chunks} setChunks={setChunks} />

      <AnimatedParticles />

      {/* Bottom hint */}
      <motion.div
        className="text-center mt-8"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1 }}
      >
        {isAIChunked ? (
          <p className="text-white/50 text-sm">
            AI has analyzed your resume and extracted key highlights. Feel free
            to edit or add more!
          </p>
        ) : (
          <p className="text-white/50 text-sm">
            Here are some examples edit them to make them your own!
          </p>
        )}
        <p className="text-white/50 text-sm">
          Tap any highlight to edit • Hover and click X to delete • Max 50 words
          per highlight
        </p>
      </motion.div>
    </motion.div>
  );
}
